version: 2

models:
  - name: stg_model_4
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: "concat(coalesce(id,1),' - ','test_sql_column')"
        tests:
          - unique

  - name: int_model_4
    columns:
      - name: id
        tests:
          - unique
          - not_null
