name: 'dbt_project_evaluator'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_project_evaluator:
    dag:
      +materialized: table
    graph:
      intermediate:
        int_direct_relationships:
          +materialized: "{{ 'table' if target.type == 'bigquery' else 'view' }}"

vars:
  documentation_coverage_target: 100
  test_coverage_target: 100
  max_depth_bigquery: 9
  staging_folder_name: staging
  intermediate_folder_name: intermediate
  marts_folder_name: marts
  staging_prefixes: ['stg_']
  intermediate_prefixes: ['int_']
  marts_prefixes: ['fct_', 'dim_']
  other_prefixes: ['rpt_']